### ISSUE TITLE
support Java 9

### ISSUE THREAD

**Issue by xuwei-k** [xerial/sbt-jcheckstyle#3]
sbt 0.13.14 will support Java 9 but can't use sbt-jcheckstyle. bacause `scala.util.Properties.isJavaAtLeast` throws `NumberFormatException` in Java 9. This issue fixed in Scala 2.12.1 but does not backported in Scala 2.10 and 2.11.

- https://github.com/sbt/sbt/blob/v0.13.14-RC1/notes/0.13.14.markdown
- https://github.com/scala/scala/pull/5276
- http://openjdk.java.net/jeps/223
- https://github.com/xerial/sbt-jcheckstyle/blob/0de31321292/src/main/scala/xerial/sbt/jcheckstyle/JCheckStyle.scala#L65

```
java.lang.NumberFormatException: Not a version: 9
	at scala.util.PropertiesTrait$class.parts$1(Properties.scala:176)
	at scala.util.PropertiesTrait$class.isJavaAtLeast(Properties.scala:180)
	at scala.util.Properties$.isJavaAtLeast(Properties.scala:16)
	at xerial.sbt.jcheckstyle.JCheckStyle$$anonfun$runCheckStyle$1.apply(JCheckStyle.scala:65)
	at xerial.sbt.jcheckstyle.JCheckStyle$$anonfun$runCheckStyle$1.apply(JCheckStyle.scala:62)
```

**Comment by xerial** [comment]
Thanks for the info. I'll use the latest Scala code of isJavaAtLeast to fix this

**Comment by xerial** [comment]
```error: error while loading package, Missing dependency 'object java.lang.Object in compiler mirror', required by /home/travis/.sbt/boot/scala-2.10.6/lib/scala-library.jar(scala/package.class)```

Struggling with this error in #4 

@xuwei-k Do you have any idea on how to resolve this?

**Comment by xuwei-k** [comment]
use https://github.com/retronym/java9-rt-export or https://github.com/sbt/sbt-launcher-package

- https://github.com/scalaz/scalaz/blob/8abb8154a19591cbecde550c7a7dfade2b5ccc27/.travis.yml#L57-L68
- https://github.com/sbt/sbt/pull/2951
- https://github.com/sbt/sbt-launcher-package/pull/143
